### ISSUE TITLE
How do I change the list of supervisors in the thesis?

### ISSUE THREAD

**Issue by vhientran** [chipewyan/naist_thesis_template#1]
Hi @chipewyan ,
Many thanks for sharing this NAIST thesis template. Please let me know how to edit the list of supervisors in the thesis template of this project.
 Thank you!

**Comment by vhientran** [comment]
Now I got it. Thanks!

**Comment by ctaguchi** [comment]
Hi, it's actually important point that might confuse people! I'll push a new version with the info in main.tex about how to change the list of dissertation/thesis committee members. Thanks,

**Comment by vhientran** [comment]
I got it. Thanks! :D
